### ISSUE TITLE
[BUG] Problem with "&" in search query

### ISSUE THREAD

**Issue by michalcyg** [TYPO3-Solr/ext-solr#1174]
Hi,
I am searching for example for "V&S" - http://www.typo3-solr.com/en/search/?q=v%26s .
After sorting or clicking on facets my search become "V" - probably because q parameter is not urlencoded there?

**Comment by michalcyg** [comment]
I have analyzed the code and seems to me like changing solr\Classes\Query\LinkBuilder.php getQueryLink function:

`        if (!empty($keywords)) {
            $queryGetParameter = '&q=' . $keywords;
        }
`
to
`
        if (!empty($keywords)) {
            $queryGetParameter = '&q=' . urlencode($keywords);
        }
`
should solve the problem. However I didn't analyze it so deeply to be sure it doesn't have any side effects.

**Comment by timohund** [comment]
@thanks for your investigation

**Comment by timohund** [comment]
I've analyzed this and it turned out that it is quite complex to fix in EXT:solr and quite easy to fix it in EXT:solrfluid. I've pushed my investigations into a branch of my fork:

https://github.com/timohund/ext-solr/tree/bugfix/master/1174-problem-with-and-in-search

Since this a more complex change and i don't know about all other side effects i would propose to fix this in solrfluid and keep it in EXT:solr as it is. Since we will migrate solrfluid to EXT:solr in the next release, this is also available there.

@irnnr What do you think about it? When you think we can also merge the changes without a bigger risk we could also do that.

**Comment by irnnr** [comment]
I agree, that's likely related to when helen/decode needs to happen. I'm fine to postponing this to when we merge EXT:solrfluid

**Comment by timohund** [comment]
Fixed with #1308
