### ISSUE TITLE
ResultTypeIcons not working anymore (from v3.0.1) as described in documentation

### ISSUE THREAD

**Issue by chvonrohr** [TYPO3-Solr/ext-solr#122]
We implemented the ResultTypeIcons as shown in the documentation:
https://forge.typo3.org/projects/extension-solr/wiki/TemplatingResultTypeIcons

Since version 3.0.1 html is not rendered anymore, instead the html source is shown on the website.
In 3.0.0 this was working. Tested in latest TYPO3 6.2.15.

Do we have to find a new way to realize that or is it a bug?

**Comment by dkd-dobberkau** [comment]
@timoschmidt can you check?

**Comment by timoschmidt** [comment]
@dkd-dobberkau Hi olivier i will check this.

**Comment by timoschmidt** [comment]
As a short update:

The problem seem to exist and was introduced with the following Issue:

https://forge.typo3.org/issues/39282

And pushed with this commit bf74217ef091ecda4f47c3216311ccae55f9cdab , since this is security related i would take the time think about a solution.

**Comment by timoschmidt** [comment]
@chvonrohr 

I've checked this issue and for me it looks not so easy to fix. The previous mentioned commit introduced the esacping with htmlspecialchars for title and content. In general this is good because we want to avoid html in the content in XSS. But in my opinion the location where this is done is wrong. For me it makes sence to do the filtering right after the data was retrieved from solr. I am currently working on an implementation of that in an own branch:

https://github.com/timoschmidt/ext-solr/commits/bugfix/release-3.0.x/122-resultTypeIcons-not-working-anymore (branch name bugfix/release-3.0.x/122-resultTypeIcons-not-working-anymore)

Can you maybe check if this is working for your current project?

**Comment by timoschmidt** [comment]
i've implemented most of the review feedback (except what i commented above). It would be nice, when somebody could review and approve this pull request.

**Comment by timoschmidt** [comment]
Merged to master
