### ISSUE TITLE
Check needed adjustments for `search` content element

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#128]
In 7LTS the `search` content element has been moved to EXT:compatibility6, check whether we need to adjust EXT:solr to deal with that. 

Currently EXT:solr replaces the content element.

**Comment by timoschmidt** [comment]
As discussed in skype. When installing compatibility6 on 7.6.0 and adding the content element you currently get "ERROR: Content Element type "search" has no rendering definition! "

Since the search plugin is still added we can pick this up later and adjust it.
The changes by now are in a branch (https://github.com/timoschmidt/ext-solr/tree/task/check-needed-adjustments-for-search-content-element).

**Comment by timoschmidt** [comment]
As far as i can see there is no change needed. The search Plugin is inserted in TYPO3 7.6.2 LTS with and without compatibility6 extension installed. So i think we can close this issue.
