### ISSUE TITLE
Check for deprecated methods

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#129]
Check whether we're using any deprecated methods and replace them with successors.

This also includes things that have been moved to EXT:compatibility6. We should not rely on their existence.

**Comment by timoschmidt** [comment]
The following methods are marked as deprecated:


TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->getPageRenderer() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8. - call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript#232 // TYPO3\CMS\Core\Page\PageRenderer->renderJavaScriptAndCssForProcessingOfUncachedContentObjects#3494 // TYPO3\CMS\Core\Page\PageRenderer->renderJavaScriptAndCss#1852 // TYPO3\CMS\Core\Page\PageRenderer->executePreRenderHook#1901 // TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction#2756 // call_user_func_array#4335 // ApacheSolrForTypo3\Solr\JavascriptManager->addJavascriptToPageFooter# // ApacheSolrForTypo3\Solr\JavascriptManager->buildJavascriptTags#251 // ApacheSolrForTypo3\Solr\JavascriptManager->addJsFile#182 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->getPageRenderer#214 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#1035 (typo3_src/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#1033)

19-11-15 09:31: TYPO3\CMS\Core\Html\HtmlParser::substituteSubpart() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use the corresponding method in MarkerBasedTemplateService accordingly - call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript#232 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent#3478 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process#3512 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#3567 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#860 // TYPO3\CMS\Frontend\ContentObject\UserContentObject->render#944 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction#40 // call_user_func_array#7231 // ApacheSolrForTypo3\Solr\Plugin\PluginBase->main# // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->render#120 // ApacheSolrForTypo3\Solr\Template->render#117 // TYPO3\CMS\Core\Html\HtmlParser::substituteSubpart#301 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#65 (typo3_src/typo3/sysext/core/Classes/Html/HtmlParser.php#63)

19-11-15 09:31: TYPO3\CMS\Core\Html\HtmlParser::substituteMarkerArray() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use the corresponding method in MarkerBasedTemplateService accordingly - call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript#232 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent#3478 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process#3512 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#3567 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#860 // TYPO3\CMS\Frontend\ContentObject\UserContentObject->render#944 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction#40 // call_user_func_array#7231 // ApacheSolrForTypo3\Solr\Plugin\PluginBase->main# // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->render#120 // ApacheSolrForTypo3\Solr\Template->render#117 // TYPO3\CMS\Core\Html\HtmlParser::substituteMarkerArray#285 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#125 (typo3_src/typo3/sysext/core/Classes/Html/HtmlParser.php#123)

19-11-15 09:31: TYPO3\CMS\Core\Html\HtmlParser::substituteMarker() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use the corresponding method in MarkerBasedTemplateService accordingly - call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript#232 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent#3478 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process#3512 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#3567 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#860 // TYPO3\CMS\Frontend\ContentObject\UserContentObject->render#944 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction#40 // call_user_func_array#7231 // ApacheSolrForTypo3\Solr\Plugin\PluginBase->main# // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->render#120 // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->renderCommand#84 // ApacheSolrForTypo3\Solr\Template->render#202 // ApacheSolrForTypo3\Solr\Template->renderViewHelpers#306 // ApacheSolrForTypo3\Solr\Template->renderMarkerViewHelper#428 // TYPO3\CMS\Core\Html\HtmlParser::substituteMarker#476 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#99 (typo3_src/typo3/sysext/core/Classes/Html/HtmlParser.php#97)

19-11-15 09:31: TYPO3\CMS\Core\Html\HtmlParser::getSubpart() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use the corresponding method in MarkerBasedTemplateService accordingly - call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript#232 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent#3478 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process#3512 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#3567 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#860 // TYPO3\CMS\Frontend\ContentObject\UserContentObject->render#944 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction#40 // call_user_func_array#7231 // ApacheSolrForTypo3\Solr\Plugin\PluginBase->main# // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->render#120 // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->renderCommand#84 // ApacheSolrForTypo3\Solr\Plugin\CommandPluginBase->getCommandTemplate#179 // ApacheSolrForTypo3\Solr\Template->getSubpart#130 // TYPO3\CMS\Core\Html\HtmlParser::getSubpart#972 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#46 (typo3_src/typo3/sysext/core/Classes/Html/HtmlParser.php#44)

**Comment by timoschmidt** [comment]
19-11-15 09:46: TYPO3\CMS\Backend\Sprite\SpriteManager is deprecated since TYPO3 CMS 7, will be removed with TYPO3 CMS 8

**Comment by irnnr** [comment]
ok, for 3.1 we should add conditions when using them vs. using their successors. After 3.1 we can have a next release that removes those and only uses the new methods.
