### ISSUE TITLE
[TASK] Do not ping before search

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1404]
Currently we check with ping, if the solr server is available before each search. For the performance it would be better just to catch the error, when the solr server is not available and redirect to the solrNotAvailableAction.

Todo:

* Check if action is coverd with a test, if not test it (e.g. with wrong credentials)
* Remove $this->searchService->getIsSolrAvailable() check and redirect.
* Replace with try catch block instead and redirect to solrNotAvailableAction when the search fails because of an unavailable solr server.

**Comment by dkd-kaehm** [comment]
@timohund 
there is much more to do, because there are multiple conditions before it goes to Apache Solr Response.
e.g. : following lines in [SearchResultSetService](https://github.com/TYPO3-Solr/ext-solr/blob/a052b247e7dfe7b8702b89d7ec94ab236c7551cb/Classes/Domain/Search/ResultSet/SearchResultSetService.php#L407-L415)

I would propose to reject this issue for an indefinite period...
I'll push all what I did.
