### ISSUE TITLE
Indexed data of page indexer

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#1433]
This is more a question than a bug report.

I created a custom fluid content element which reads non typo3 content and renders it on the page (using COA_INT for caching). But the page indexer only indexes the other content elements on the page. So what content gets indexed through the page indexer and what content does not get indexed?

Thanks a log in advance!

**Comment by dkd-kaehm** [comment]
Hello @klodeckl,

By indexing pages EXT:Solr tells TYPO3 FE to hide all dynamic aka non cachable CEs, because in the most cases the contents are different each time the page is requested. Moreover it could be that non cachable CEs are user relevant.

So its common to not to hold that volatile data in Index for avoiding results, which do not exist.
