### ISSUE TITLE
Wildcard search and stemming

### ISSUE THREAD

**Issue by LukasVice** [TYPO3-Solr/ext-solr#1586]
I would like to ask if you could help me with following problem:

I have a "content" field. This field is configured as type "text" which is defined in the german schema.xml including a SnowballPorterFilter.

If I search for "kalender" everything works as expected. But searching for "k?lender" or "k*lender" doesn't return any result.
I think the problem is that if a wildcard is used, the query is not analyzed. And because of the SnowballPorterFilter which does the stemming of the word, only the word "kalend" is stored in the index. So if I search for "k?lend" it works fine.

The question is, how can I get the expected results when searching for "k?lender"?

Thank you.

**Comment by klamparski** [comment]
Hello @LukasVice.

Did you resolved it somehow? I have exact same problem and looking for a solution.

**Comment by dkd-kaehm** [comment]
Hey folks! Please tell others about used EXT:Solr versions.

**Comment by dkd-kaehm** [comment]
Hey Folks since EXT:Solr 6.1 there is contentExact Field and corresponding dynamic Field-Types([_textExactS](https://github.com/TYPO3-Solr/ext-solr/blob/ebcd1ac5ae4e1aba9854a1f170ae2ee17140100b/Resources/Private/Solr/configsets/ext_solr_8_0_0/conf/general_schema_fields.xml#L231)).
Those are without stemmer and they can be used for your case.
Just add the fields to the queryFields:
```
plugin.tx_solr.search.query.queryFields := addToList(contentExact\^20)
```

**Comment by klamparski** [comment]
Worked. Thank you @dkd-kaehm.
