### ISSUE TITLE
[BUG] Search in Japanese and Chinese is case sensitive

### ISSUE THREAD

**Issue by mvoehringer** [TYPO3-Solr/ext-solr#1789]
Hi, 
I am working on an project with and Japanese and Chinese version. Now we have problems with some queries in these languages. If you search for an page with the title "Product Name" you can only find it if you search for "Product Name". The search "product name" did not return an result. (the product names are english). I think the problem is the missing `<filter class="solr.LowerCaseFilterFactory"/>` in the Japanese  schema.xml file.  

https://github.com/TYPO3-Solr/ext-solr/blob/master/Resources/Private/Solr/configsets/ext_solr_8_0_0/conf/japanese/schema.xml

We are using the Docker image typo3solr/ext-solr:6.5.0.

**Comment by 3l73** [comment]
Hi,

Kanji (chinese and japanese characters) are not separated into upper or lower case.
However, Hiragana and Katakana (japanese syllable characters) have upper and lowercase characters. These are working different as latin characters.

The syllable *tsu* (つ) for example have a different meaning if you use the lowercase character.
If you use uppercase it will read as *tsu*. If you write it in lowercase it doubles the following syllable.

Here an example:
If you write Nippon with Hiragana you get にっぽん
Convert it into upper or lowercase it will change into Nitsupon (につぽん). In this case the whole **meaning** of the word changed!

Another example is Ferry:
Written in Katakana you get フェリー (Fueri-). Since there is no *fe* syllable, a combination of *fu* and a small *e* is used to get the reading of *fe*

If the filter for lower case only effects the latin characters it will work. If it effects Hiragana and Katakana that *will lead in some cases to incorrect search results*.

Regards

Elte

**Comment by timohund** [comment]
@3l73 What is your suggestion then? As far as i understand it's correct without the lowercase filter?

**Comment by 3l73** [comment]
It depends on how the filter is working.
If the filter did not effect Kanji, Hiragana and Katakana it can be used.
Otherwise it should be checked if there is a filter that only effects latin chracters.

**Comment by bandanh** [comment]
Hi, I just stumbled over this Issue and made a quick test.
When I search `フエリー` , Ferry with a typo, capital E instead of e, in google, then I get a `did you mean フェリー`. Maybe Solr is smart enough to do the same.

https://www.google.com.kh/search?q=%E3%83%95%E3%82%A8%E3%83%AA%E3%83%BC

**Comment by timohund** [comment]
@bandanh @3l73 
When i process "につぽん TestLatin" with the LowerCaseFilter, the result is "につぽん testlatin" so for me it looks like, that only latin charcters get lowercased. When i understand your comments right, it should be ok the lowercase those characters right?

**Comment by mvoehringer** [comment]
@timohund Are you still working on this? To me it looks like we can add the solr.LowerCaseFilterFactory filter for asian languages.

**Comment by timohund** [comment]
@mvoehringer i was waiting for feedback, and as you gave this now, i would say, let's do that ;)

**Comment by timohund** [comment]
@mvoehringer  can you please test #2101 ? Then we can merge it into the master branch.
