### ISSUE TITLE
"Show more" - JavaScript not includable without additional facets

### ISSUE THREAD

**Issue by KaEdSei** [TYPO3-Solr/ext-solr#1791]
The "Show more"-Button is rendered by default if more then 10 options are available. By default the JavaScript is not included, rendering this button useless. So either the button shouldn't be added or the JavaScript included by default.

**Comment by timohund** [comment]
@KaEdSei 

As desribed in https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Frontend/Concepts.rst EXT:solr ships several examples how facets can be configured. The final configuration and integration is in the response of the integrator, since he decides how javascript and css should be loaded. Therefore the Example https://github.com/TYPO3-Solr/ext-solr/blob/master/Configuration/TypoScript/Examples/Facets/Options/setup.txt for an options facet also loads the javascript controller that does the collapsing. If you need it differently you could change it by overwritting the partials in your project.
