### ISSUE TITLE
Translation files shall be on translations.typo3.org

### ISSUE THREAD

**Issue by patkar** [TYPO3-Solr/ext-solr#191]
There is no reason why they should not be on translations.typo3.org..

**Comment by timoschmidt** [comment]
@patkar The files are now available on translation.typo3.org currently the conversion to xlf files is an open issue (https://github.com/TYPO3-Solr/ext-solr/issues/93). 

When you have time to provide a PR feel free to do that an maybe just give us a hint here or in the slack channel that you started working on it. Otherwise we do this during the next days.

**Comment by timoschmidt** [comment]
Translation files are available on translation.typo3.org and labels have been converted to xliff
