### ISSUE TITLE
Support hl.useFastVectorHighlighter in Query

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#193]
Since the performance of highlighting could get very poor (e.g. when you are using grouping and highlighting together) and some fields have the required schema settings, we should support this option in the highlighting configuration.

**Comment by irnnr** [comment]
Please don't make this configurable, simply replace the existing highlighter.

**Comment by dkd-friedrich** [comment]
IMHO it could be advantageous to support both types, since the FastVector Highlighter requires a fragment size of 18, doesn't accept 0 and so always restricts the field length. 

Additionally it changes the behavior to switch to the FastVector Highlighter by default, the commonly used setting of "fragmentSize = 0" will result in errors and requires configuration adaptions on extension update.

**Comment by timoschmidt** [comment]
I would agree to markus because the FastVectorHighlighter only works for fields with a specific configuration (termVectors=on, termPositions=on and termOffsets=on) and this would mean highlighting is not possible for other fields.

**Comment by irnnr** [comment]
I think that's fine. Right now that applies only to the content field, it might make sense to also configure the title field this way. 
Either way, I'd like to keep the extension simple for the enduser; convention over configuration. The extension does work one specific way and is supposed to fit >90% of use cases out of the box. If someone needs something more special there's always a way to customize through code by registering different classes, using hooks or using xclasses.

Making highlighting configurable is too low-level for the 90%.

**Comment by timoschmidt** [comment]
So what is your proposal for the default then?

- Set termPositions="true" termOffsets="true" also on title
- Use fastVectorHighlighter when fragSize ist larger then 18 otherwise 
- fallback to normal highlighter when fragsize is smaller then 18 or highlighting field except title or content is passed

I think the advantage would be that fastVectorHighlighter will be used out of the box, but the downsides are, that the code is directly coupled to the schema and the usage is limited to a few fields.
 
I think as it is right now, it makes sence for most of the systems, because it is disabled by default and for most cases the performanceof highlighting is ok. Only when not, you need to enable it and in this case you should know what you do. 

In general it makes sence to avoid the complexity in the configuration but for me the usage of fastVetorHighlighter has to many edge cases to use it by default.

**Comment by irnnr** [comment]
Highlighting on `title` never worked so far, so if we could get that fixed that'd be nice.
Solr's `fragsize` default is 100, so that should not be a problem.
I don't expect anyone trying to do highlighting on anything besides `title` and `content` - at least I've never seen anything else or saw someone ask for any other fields so far. Most of the time these will also be the only fields in the SERP listing. Given that it's not working on title ATM it only leaves `content`.

Given these preconditions I'd say it's safe to make `fastVetorHighlighter` the default. 

I've seen (performance) issues with the current highlighter when highlighting `content` fields for documents of files, these tend to be a lot larger than documents of TYPO3 pages. I hope using fastVetorHighlighter could fix that.

I'm not worried about coupling to the schema, that's the case already anyway and is just a given; the extension relies on a specific schema being present to work properly. However, maybe we could think about adding custom fields that allow highlighting using `fastVectorHighlighter` for those who need them.

**Comment by irnnr** [comment]
I'll try to take care of this. 

Adding the documentation link for reference: https://cwiki.apache.org/confluence/display/solr/FastVector+Highlighter

**Comment by dkd-dobberkau** [comment]
Sounds reasonable!
