### ISSUE TITLE
[FEATURE] Add TS settings (for pagebrowser) to Fluid templates

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [TYPO3-Solr/ext-solr#1945]
https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrSearch.html#results-pagebrowser refers to *EXT:pagebrowse* which was replaced by `s:widget.resultPaginate` ViewHelper.

I didn't find a way to pass TS configuration options e.g. `plugin.tx_solr.search.results.pagebrowser.insertAbove = 0` to the `configuration` attribute of `s:widget.resultPaginate` in Search/Results.html.

Assigning all TS settings in [SearchController->resultsAction()
](https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Controller/SearchController.php#L94) (or in `initializeView()`) would be very useful.

**Comment by timohund** [comment]
@georg-tiefenbrunn I think we should remove those settings from the documentations, since they are obsolet. For what do you need these settings? You could resolve this with FLUID core functionality by using different partials.

**Comment by georg-tiefenbrunn** [comment]
@timohund Using multiple versions of a 125 lines Fluid template to alter the behavior of a viewHelper imho is an overkill. To "resolve this with FLUID core functionality" you should move the `s:widget.resultPaginate` part in https://github.com/TYPO3-Solr/ext-solr/blob/master/Resources/Private/Templates/Search/Results.html into its own partial so integrators could easily configure the pagination without overwriting all the other cool stuff you've built into EXT:solr (sorting, facets, spell checking suggestions, auto correction etc.).

Providing basic TS settings (e.g. `plugin.tx_solr.search.results` as `settings` in `SearchController->resultsAction()`) enables us to use `<s:widget.resultPaginate resultSet="{resultSet}" configuration="{insertAbove: '{settings.pagebrowser.insertAbove}', insertBelow: '{settings.pagebrowser.insertBelow}'}">`:

* No additional partial needed (performance)
* No template must be altered (hassle-free extension update)

**Comment by timohund** [comment]
@georg-tiefenbrunn I think moving the s:widget.resultPaginate part into an own partial makes sence, because it also simplifies the template structure.
 
Regarding the other settings 'insertAbove' and 'insertBelow' i think this is something, that should be in control of the template because when we add this for everything we end up with a lot of flags.  We tried to avoid that for facet partials and areas as well and introduce convensions instead.

Having this in a partial would only mean to remove one line from the template. In terms of performance this is even faster because it will not be evaluated at all, not in the template and not in the code for the settings.

If you need to use the settings approach you could even define you own setting and evaluate it in the template.

**Comment by infabo** [comment]
You more or less built the result-pagination to act like the core pagination widget - but with hardcoded values in `AbstractPaginateWidgetController`. Then arguing "the template should be responsible" is like a really cheap excuse.

**Comment by dkd-kaehm** [comment]
@infabo 
I don't quite understand your comment.
What do you want to deliver? Please open a new issue or a pull request.
