### ISSUE TITLE
Add upgrade information for breaking changes

### ISSUE THREAD

**Issue by mschwemer** [TYPO3-Solr/ext-solr#2091]
Ir would be good, if there would be a some upgrade documention for breaking changes. In my case it were the following things from 7.5 to 8.1.:

* Renamed layout: Main => Fullwidth
* Renamed section: main => content
* Changed html markup and css classes for autosuggest 

It did not take much time to find that out, but it would have been more convenient to have this info upfront. 

Other areas did not hit me ...  ;-)

**Comment by timohund** [comment]
Hi Markus, i understand that partly. By now we try to make the release very detailed. The thing is, at what time a changes is breaking?

The change you are mentioning was added with the migration to bootstrap (in version 8). I understand what breaks in this case, but... ...when you exclude all Templates, Partials, Layouts and css because you customize it with your project this problem should not exist because it would still run with a newer version of EXT:solr. Also when you just use the default Partials, Templates and Layouts it is not a problem. I think this "only" happens when you use a combination of default and customized Templates, Layouts and Partials (and i understand that this makes sence). 

Maybe you can help before the EXT:solr 9 release and have a look on the release notes before the release? By now i unfortunately got now feedback on the request for testing a feedback in slack.

**Comment by timohund** [comment]
@mschwemer The upgrade steps are documents in the release notes: https://github.com/TYPO3-Solr/ext-solr/pull/2174 it would be nice when you can try to do an upgrade and provide a pr if you miss something. Therefore i'll close this issue
