### ISSUE TITLE
Setting searchUsingSpellCheckerSuggestion=0 has no effect

### ISSUE THREAD

**Issue by gaumondp** [TYPO3-Solr/ext-solr#2198]
We have search.spellchecking.searchUsingSpellCheckerSuggestion=0 but Solr still give results for second result.

Example: "carra" is a meta-keyword and not in any content. As written, we set searchUsingSpellCheckerSuggestion=0 and our result page found the page but also has a "Did you mean 'carre'" and then also shows second results and so on for "carre.

From documentation, it should only show 1 result and 1 only for "carra".
See: https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrSearch.html#spellchecking-searchusingspellcheckersuggestion

**Comment by gaumondp** [comment]
Yes I did. Here is the TS Object browser view:

```
[spellchecking] = 1 
[numberOfSuggestionsToTry] = 0
[searchUsingSpellCheckerSuggestion] = 0
```

You can see it there: https://www.quebec.ca/resultats-de-recherche/?L=0&id=1415&tx_solr%5Bq%5D=carra

**Comment by timohund** [comment]
I think the reason is that the initial resultset allready has results, autocorrection only happens when the initial query does not produce any results. I think we need to take a closer look on the setup to figure out what is the case there. 

I've checked the functionallity on my system and there is an integration test for that as well (SearchControllerTest::canAutoCorrectATypo)

If you need further assistance we can offer you support by dkd (solr-eb-support@dkd.de)

**Comment by gaumondp** [comment]
We "fixed" the problem with this TS:

```
plugin.tx_solr.index.queue.pages.fields.keywords_textExactM = SOLR_MULTIVALUE
plugin.tx_solr.index.queue.pages.fields.keywords_textExactM {
    field = keywords
}
plugin.tx_solr.search.query.queryFields = keywords_textExactM^80.0, titleExact^50.0, description^50.0, tagsH1^25.0, tagsH2H3^20.0, contentExact^10.0, abstract^10.0, subtitle^2.0, tagsH4H5H6^2.0, tagsInline^1.0, navtitle^1.0
```
