### ISSUE TITLE
Index in filters changes with setFaceItemVH if facet name was already used

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#2208]
Scenario:
* facets are rendered as select tag
* some tagging and excludeTags magic is used
* facets are set with the setFaceItemVH
* you select an item of the first facet (foo)
* you select an item of the second facet (bar)
* you change the item in the first facet (foo)

Result:
?tx_solr[filter][1]=bar:demo&tx_solr[filter][2]=foo:demo

and no search results

Expected result:
?tx_solr[filter][1]=bar:demo&tx_solr[filter][0]=foo:demo

**Comment by dkd-kaehm** [comment]
@Mabahe hi,
I can currently not reproduce this issue, the key of filter does not influence the result-set.

I think its expected behaviour, that the amounts of result sets of used facets not equal. 
Also the amount of 
`foo:1 AND bar:1` = X Results 
`foo:2 AND bar:1` = 0

Tipp: Disable the links for facet-options without results.

I'll close this issue.
Please feel free to comment this issue with in detail example if you can reproduce this issue. 
We'll reopen this issue to implement a test case.
