### ISSUE TITLE
[BUG] TYPO3 9 - Wrong cHash on site using SiteConfiguration

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#2211]
On TYPO3 9, within a site using SiteConfiguration, all pagination or facet links are appended with a cHash.

```
https://mysite.local/global-search?tx_solr%5Bpage%5D=2&cHash=2083113c1e281718add2e591b3c7bf0f
```

This is new behaviour on TYPO3 9 introduced by the new routing handler. (see https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html#impact

The issue is also described on the forge: https://forge.typo3.org/issues/87120
It is clearly stated that useCacheHash=0 is now useless when generating a uri!

I open this issue in order to track the problem into milestone 9.
I know that siteHandling is not fully supported yet in dev-master, but this issue is very anoying, because everyone want to have pretty url, and we can not acheive this on v9 without a SiteConfiguration.

**Comment by dogawaf** [comment]
Also, inspecting the uri building in ext:solr, I found that `\ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder::buildLinkWithInMemoryCache()`, while trying to save some typolink calls, will now break by default the cHash calculation.
For my usescases, disabling this method solves temporarly the issue, by appending right cHash to pagination and facet URIs.

**Comment by LukasVice** [comment]
Same problem.

As a workaround, add `tx_solr[q]` and `tx_solr[page]` to `FE/cacheHash/excludedParameters` in the `LocalConfiguration.php`.

**Comment by helhum** [comment]
> As a workaround, add tx_solr[q] and tx_solr[page] to FE/cacheHash/excludedParameters in the LocalConfiguration.php.

This works, but does not work for facets, which is an array argument. See https://forge.typo3.org/issues/87120

**Comment by helhum** [comment]
> Problem is in EXT:solr/Classes/Domain/Search/Uri/SearchUriBuilder.php, function buildLinkWithInMemoryCache

Yes, in this method, cHash argument should be removed for TYPO3 9.5 compatibility

**Comment by helhum** [comment]
@timohund What bugs me with the solution merged with #2222 is that solr with TYPO3 9.5 has worser performance when building links and unnecessary identical page cache entries are created for the multitude of links generated, especially when using facets.

A very straightforward solution would be to create a link template, and remove the cHash argument in case it was set. With that, even the compatibility checks could be removed as this would work in 8 and 9 as well.

Any reason this isn't done like that?

**Comment by helhum** [comment]
I haven't checked the performance impact. It might be negligible.
However generating cHash links, when this is not needed and each cHash link producing a separate (and identical) cache entry does not seem right to me.

Anyway. Thanks for the fix.

**Comment by timohund** [comment]
@helhum Thanks for you feedback. Can you maybe describe more in detail what you mean? As far as i understood by now every link in TYPO3 9 would need a cHash, so even when we cache it we would need to calucate that for every link. Or is this wrong?

The ideas behind that caching was, that we generate a lot of "nearly" identical links in solr and therefore a lot of typolink calls, what is very expensive. Therefore we build this link with a structure that just contains markers that will be replaced later. Which works totals fine without cHash and at the time when it was implemented it saved **a lot** of performance especially when you have a lot of facet options.  Replacing the call of typolink with arguments instead of structure would keep the caching but i guess i till produce nearly no cache hit since exactly the same link is not generated twice. So i think this does not make sence.

It would be nice to have an option that still allows to cache the "link structure" with the compatibility of the required changes for 9 LTS / SIteHandling regarding the cHash.

**Comment by helhum** [comment]
> As far as i understood by now every link in TYPO3 9 would need a cHash, so even when we cache it we would need to calucate that for every link. Or is this wrong?

This is indeed wrong. As a tried to point out [here](https://github.com/TYPO3-Solr/ext-solr/issues/2211#issuecomment-452362122) and [here](https://github.com/TYPO3-Solr/ext-solr/issues/2211#issuecomment-454742644), **removing** the cHash from the URL is a proper fix (not adding a cHash to each URL).

In link building solr code sets configuration to not append a cHash, but this is API, despite it still exists, ist not effective in TYPO3 9.5 and therefore a cHash is appended, causing all the trouble, because once a cHash is in the URL, it will be checked. If it is not in the URL and no URL argument requires a cHash, the URL is accepted.

Point here also is that the complete solr plugin is uncached. Which means there is **no need** to add a cHash to each URL for the solr plugin, because it will be executed and not delivered from cache.

When now cHash argument is added to each URL, then each requested URL with a valid cHash will create a page cache entry (in which the solr plugin is marked as uncached and stored as placeholder), thus multiple identical cache entries are generated, when there is no need to do so. With facets, this leads to an almost ifinite number of cache entries potentially generated, when tx_solr[q] is not excluded from cHash generation (which it isn't by default).

But even with this argument excluded, there would be more than a handful of unnecessary cache entries, when having some factes and a reasonable amount of search entries for multiple facte combinations. And there are further arguments, like pagination or filtering, so the number of not needed cache entries could add up pretty quickly (again given they are not excluded from cHash, which is possible for most, but not arguments that represent an array).

**Comment by DanielSiepmann** [comment]
This was now fixed for TYPO3 10 only: https://review.typo3.org/c/Packages/TYPO3.CMS/+/63062
We wanted to have a cached version of the plugin, which does not work with pagination due to hard coded removed `cHash` argument.

Should we re open this issue, or create a new one?

Right now we apply the following patch to EXT:solr:

```patch
Support cHash generation in all links.

The mentioned issue is already solved.
One should and can configure excludedParameters with regex. So e.G.:

    'FE' => [
        'cacheHash' => [
            'excludedParameters' => [
                'solr' => '^tx_solr',
            ],
        ],
    ],

diff --git a/Classes/Domain/Search/Uri/SearchUriBuilder.php b/Classes/Domain/Search/Uri/SearchUriBuilder.php
index 81eb4321..7fc5246a 100644
--- a/Classes/Domain/Search/Uri/SearchUriBuilder.php
+++ b/Classes/Domain/Search/Uri/SearchUriBuilder.php
@@ -310,36 +310,22 @@ class SearchUriBuilder
      */
     protected function buildLinkWithInMemoryCache($pageUid, array $arguments)
     {
-        $values = [];
-        $structure = $arguments;
-        $this->getSubstitution($structure, $values);
-        $hash = md5($pageUid . json_encode($structure));
+        $hash = md5($pageUid . json_encode($arguments));
         if (isset(self::$preCompiledLinks[$hash])) {
             self::$hitCount++;
             $uriCacheTemplate = self::$preCompiledLinks[$hash];
         } else {
             self::$missCount++;
-            $this->uriBuilder->setTargetPageUid($pageUid);
-            $uriCacheTemplate = $this->uriBuilder->setArguments($structure)->setUseCacheHash(false)->build();
-
-            // even if we call build with disabled cHash in TYPO3 9 a cHash will be generated when site management is active
-            // to prevent wrong cHashes we remove the cHash here from the cached uri template.
-            // @todo: This can be removed when https://forge.typo3.org/issues/87120 is resolved and we can ship a proper configuration
-            $urlHelper = GeneralUtility::makeInstance(UrlHelper::class, $uriCacheTemplate);
-            $urlHelper->removeQueryParameter('cHash');
-            $uriCacheTemplate = $urlHelper->getUrl();
+            $uriCacheTemplate = $this->uriBuilder
+                ->setTargetPageUid($pageUid)
+                ->setArguments($arguments)
+                ->setUseCacheHash(true)
+                ->build();
 
             self::$preCompiledLinks[$hash] = $uriCacheTemplate;
         }
 
-        $keys = array_map(function($value) {
-            return urlencode($value);
-        }, array_keys($values));
-        $values = array_map(function($value) {
-            return urlencode($value);
-        }, $values);
-        $uri = str_replace($keys, $values, $uriCacheTemplate);
-        return $uri;
+        return $uriCacheTemplate;
     }
 
     /**
```
