### ISSUE TITLE
Info module throws exception if solr cores not available for one language

### ISSUE THREAD

**Issue by maritwho** [TYPO3-Solr/ext-solr#2220]
In the info module the connection to all configured solr cores for the different languages is checked. If one core does not exist on SOLR server an exception is thrown. But this exception has to be catched by the info module to show, which solr cores are available and which not.

Currently this exception (SolrCommunicationException) is not catched. This crashes the info module if just one core is not available.

Found with TYPO3 8.7.x and ext:solr version 8.1.2

**Comment by dmitryd** [comment]
I have this too. This is especially annoying of you have a number of sites with different translation requirements (like one site has DE/EN/FR/IT and another has DE/FR). Then you would not configure solr core for the languages that are not needed for a particular site. And it gives exceptions.

The only non-patching solution I found is to set `plugin.tx_solr.enable = 0` globally and set it to `1` using conditions per root page and language. Like this:

```
# Enable per site/language
[globalVar = GP:L = 0]
# German is always enabled
plugin.tx_solr.enabled = 1
[1 in tree.rootLineIds]
plugin.tx_solr.enabled = 1
[PIDinRootline = 54] && [globalVar = GP:L = 2, GP:L = 3]
# site 2
plugin.tx_solr.enabled = 1
[PIDinRootline = 56,57,58] && [globalVar = GP:L = 2]
# site 3, site 4, site 5
plugin.tx_solr.enabled = 1
[END]
```

Notice all the mixture of the old and new condition syntax. The problem is that in TYPO3 9.5 solr still uses `$_GET['L']` while indexing but the system normally does not have `L` at all.
