### ISSUE TITLE
[BUG] Warning htmlspecialchars()

### ISSUE THREAD

**Issue by kassor** [TYPO3-Solr/ext-solr#2318]
**Describe the bug**
I got this warning message in sys_log

**To Reproduce**
Warning is called if solr search will be triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/15608529/58242528-454be180-7d4f-11e9-8b03-35b1eaa5add4.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7.26
 - Browser: chorme
 - EXT:solr Version: 9.0.2
 - EXT:solrfluidgrouping Version: 2.0.0
 - PHP Version: 7.2.17

**Comment by dkd-kaehm** [comment]
Can't reproduce that issue:

Tried on [solr-ddev-site](https://github.com/TYPO3-Solr/solr-ddev-site): 
 With possible suggestion action -> 
https://solr-ddev-site.ddev.site/content-examples/form-elements/search?type=7384&tx_solr[callback]=jQuery31105003996379572146_1630591569882&tx_solr[queryString]=tes&tx_solr[additionalFilters][0]=type:pages&tx_solr[additionalFilters][1]=-fakeField:none

The row 
`$additionalFilters = is_array($additionalFilters) ? array_map("htmlspecialchars", $additionalFilters) : [];`
seems to be clean for proper usage of additionalFilters URI parameters.

See the implementation since EXT:Solr 9.0.2:
https://github.com/TYPO3-Solr/ext-solr/blob/76f041f09f7b63295259c35e707581009e18f2e7/Classes/Controller/SuggestController.php#L41-L76
