### ISSUE TITLE
[BUG] Do only index enabled Languages configured in Site Handling

### ISSUE THREAD

**Issue by achimfritz** [TYPO3-Solr/ext-solr#2391]
**Describe the bug**
Languages set to "disabeld in Frontend"  in Site Handling Configuration should not be tried to indexed.

**To Reproduce**
1. create a Frontend-Page in the Site Module and disable "Visible in Frontend "
2. Try to index that Page results in an Error

**Expected behavior**
the language should not be indexed

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5
 - EXT:solr Version: dev-master

**Comment by NochEinKamel** [comment]
I have some more issues with enabled/disabled languages.

I'm working on a project using several disabled languages (including the default language) where ext-solr doesn't work out of the box (dev-master).

An example setup would be a Site config with languages:
[0] Base English (not enabled/Visible in Frontend) [default language]
[1] Base German (not enabled/Visible in Frontend)
[2] Germany - German (enabled; strict Fallback to Base German)
[3] Germany - English (enabled; strict Fallback to Base English)
[4] Switzerland - German (enabled; strict Fallback to Base German)
(and many more...)

For normal content pages only languages 0 and 1 are entered;
If there is a different content for the german page in Switzerland then the editors enter that content in language 4.
The frontend is only ever called in languages 2, 3 and 4 and typo3 automatically shows the entered content respecting the fallback even if the fallback language is disabled.

ext-solr currently ignores languages with disabled fallback languages except if the fallback is the default language.

---- 

If language 0 is disabled the Indexer errors out with:
`1552491117: ApacheSolrForTypo3\Solr\NoSolrConnectionFoundException: Could not find a Solr connection for root page [1] and language [0].`

This is caused by the Indexer class fetching the default connection with language id 0:
`$defaultConnection = $this->connectionManager->getConnectionByPageId($pageId, 0, $item->getMountPointIdentifier());`
The quick fix is put an empty try-catch around the line to catch the exception and ignore the defaultConnection (including the following if statement).
Nor sure how deep the real fix would have to go as there seem to be a lot of "if language == 0" statements and even getDefaultLanguageUid returns 0; in this setup there is not really a default language or "default connection".

----

Another issue is that only languages which explicitly have content or which a fallback to language 0 are considered and not those which have no content but a disabled fallback language with content.

e.g. Base German has content but Germany German not, then neither are indexed.
But if Base English has content and Germany English not, Germany English is indexed anyways.

This is all down to the method `getTranslationOverlaysWithConfiguredSite` in the Indexer class.
The fallbacks only consider overlays which are enabled but should really consider all available overlays.

----

I have made code changed for bth issues in my local clone, but I'm too stupid to push them to github currently :-D
So here is a gist: https://gist.github.com/NochEinKamel/5a342378febb390d1fa2e2df4e6cbc10
In the first method I've only changed the lines marke with /**...**/
The second method is a reimplementation which is currently only tested for my use case.

**Comment by NochEinKamel** [comment]
@timohund Should I open a new issue for my last comment? I added it here because it's basically a test for this issue

**Comment by timohund** [comment]
@NochEinKamel it would be nice if you could open a new issue for that including your comments and the reference to you're gist. I think that your remarks are valid points but since they are not a very common case we should handle that in a dedicated issue and also shoould include several tests for that. As far as i understand your setup right, you want to have multiple default sites (one for each language with different variants available)
