### ISSUE TITLE
[TASK] Check handling of absRefPrefix and fix functional tests

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2395]
**What should be done in the scope of this task?**

IndexServiceTest::canResolveAbsRefPrefix is skippen with the migration to site handling(#2390). We should clarify, what is the expected behaviour here and fix it, if it is a bug or adapt the testcase if not.

**Comment by dkd-kaehm** [comment]
On Site-Handling configured sites the `config.absRefPrefix` is not necesarry and should be removed from TypoScript, as they are ignored if site-handling is enabled:

---

See: 
https://forge.typo3.org/issues/86057

https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/9.4/Feature-86057-ImprovedTypolinkURLLinkGeneration.html

**Due to the new page-linking functionality, the following TypoScript settings are not necessary anymore and should be removed for TypoScript configurations on page trees with a site configuration:**
* Including the “L” parameter in config.linkVars, as the L parameter is not evaluated for page requests with a site configuration.
* `config.absRefPrefix` **is only necessary for links to files or images, but not for page links, as they are always built against the absolute path, or - if typolink.forceAbsoluteUrl is explicitly set. The option is set to auto by default for site configuration TypoScripts, so this is not necessary anymore in regular installations.**
* One of the major strengths allows to link across sites / domains with specifically knowing all available languages of a different page tree. Using the config.typolinkEnableLinksAcrossDomains is not necessary anymore for TypoScript within a site configuration.

---

I'll remove this test and provide new one with `base` and pack a hint about that in the release notes.
