### ISSUE TITLE
[FEATURE] Toggle Solr 10.x with environment variables

### ISSUE THREAD

**Issue by einpraegsam** [TYPO3-Solr/ext-solr#2538]
EDIT: Sorry, wrong version - I mean 10.0.1 for EXT:solr

In sites/name/config.yaml we can add a solr configuration like
```
solr_enabled_read: false
solr_host_read: '%env(SOLR_HOST)%'
solr_path_read: /solr/
solr_port_read: '%env(SOLR_PORT)%'
solr_scheme_read: https
solr_use_write_connection: false
```

While EXT:solr should run on some instances, it should be disabled in other instances (without a connection). At the moment it's not possible to use environment variables for solr_enabled_read as far as I see. So we have to deploy true or false on all instances.

If I'm wrong, pls give me a hint.

Alex

**Comment by dkd-friedrich** [comment]
I can confirm this issue, as values from environment variables are treated as strings it's not possible to e.g. deactivate a Solr connection.

Since incoming string "false" is evaluated as `true` by the `SiteRepository` and it's not possible to set "0" due to evaluations in the `YamlFileLoader`. we have to adapt the evaluation in the `SiteUtility`.

**Comment by mschwemer** [comment]
Hi,

this path does not do, what we expected :-(

The current situation is as follows: 

Setting the `solr_enabled_read` via environment variables leads to the following situation, that in the module "Site" the `enabled` switch is always disabled and in the module "Apache Solr" the connections are always active. There is no difference, whether I set the env variable to true or false. See attached screenshots ...

![solr_enable-true_info-module_2020-04-15_16-39](https://user-images.githubusercontent.com/103594/79352914-b59cbc00-7f3a-11ea-85b4-d01d11810db2.png)
![solr_enable-true_siteconfig_2020-04-15_16-37](https://user-images.githubusercontent.com/103594/79352917-b6cde900-7f3a-11ea-8d7a-42fb3e630300.png)
![solr_enable-true_code_2020-04-15_16-37](https://user-images.githubusercontent.com/103594/79352920-b7667f80-7f3a-11ea-9ca6-75df303d1232.png)

If I set `solr_enabled_read` directly (without environment variables), I get the situation from the following screenshot:

![solr_settings-via-environment_2020-04-15_17-00](https://user-images.githubusercontent.com/103594/79353155-f7c5fd80-7f3a-11ea-83df-0f1ccdccc64f.png)

- Scheme says "invalid value":  the site configuration says ist must be either "http" or "https"
- Solr-Port is red because it is set via an env variable and thus blocks saving the whole site configuration ... the site configuration says ist must be of type "int"

See `EXT:solr/Configuration/SiteConfiguration/Overrides/sites.php`

**Comment by mschwemer** [comment]
I had a very friendly call with @dkd-friedrich. Thanks.

These are two topics:

- display in the site configuration
- handling of the .env variable in our local dev environment

The first one will be han  in an separate issue. 
The second one was a mis-conception about my local dev enviroment. The variables from .env are only read at the start of a docker container.

**Comment by dkd-friedrich** [comment]
@mschwemer Thanks for your detailed descriptions. As already discussed the handling of the environment variables in the site management is not directly related to the general evaluation of the variables focused in this issue.

Of course you're right, environment variables are not correctly handled in the site configuration and this should be adapted. I've opened a new issue for that: #2576
