### ISSUE TITLE
JavaScript files get lost if concatenation and compression are enabled

### ISSUE THREAD

**Issue by jloderhose** [TYPO3-Solr/ext-solr#264]
If the TYPO3 build-in compression and concatenation for JavaScript assets is enabled, the resulting files do not contain JavaScript included via plugin.tx_solr.javascriptFiles. Also, the files aren't included in the resulting HTML by individual tags. They're missing altogether. Without compression/concatenation all looks well.

I experience this behavior with TYPO3 6.2.19 and solr 3.1.1. The issue appeared any time in the past without me noticing. I cannot tell when it actually arose.

Is there a known cause to this behavior or is it a bug?

**Comment by timoschmidt** [comment]
@jloderhose 

For me this looks like that it's a leftover from adaptions to the pageRenderer.

changing 

 'file' => GeneralUtility::createVersionNumberedFilename($GLOBALS['TSFE']->tmpl->getFileName($fileReference))

to 

 'file' => $GLOBALS['TSFE']->tmpl->getFileName($fileReference)


Looks like to solve it, because the file version is still generated form the PageRenderer. Can you maybe verify? I think we should add an integration test to cover that an fix it.

**Comment by timoschmidt** [comment]
Bug was fixed on release-3.1.x branch, we need to fix it on dev-master as well.

**Comment by jloderhose** [comment]
@timoschmidt I'm very sorry, I did not reply earlier. I did not realize, my e-mails did not sync. My bad!
Thank you very much for taking care of this issue regardless of my silence! :+1:
