### ISSUE TITLE
[BUG] ConnectionManager->getConnectionByPageId fails if default language is disabled in SiteConfiguration

### ISSUE THREAD

**Issue by pulponair** [TYPO3-Solr/ext-solr#2793]
**Describe the bug**
If the default language is not pressent in SiteConfiguration 
ConnectionManager->getConnectionByPageId fails in frontend context.

This is probably caused by the fact that the language isn't passed trough to 
SitRepository::buildTypo3ManagedSite and the language 

**Note:**
That does not happen if the SiteRepository runtimeCache has been warmed up front from the backend by e.g. clicking the backend solr info module.

**To Reproduce**
- Create site configuration without default language 
- Place searchform plugin 
- Surf Frontend
- See "Search is currently not available."

**Expected behavior**
Searchbox should appear

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.20
 - EXT:solr Version: 

**Additional context**
Related to #2596.

**Comment by dkd-kaehm** [comment]
@pulponair 
Thanks for reporting. 
Your EXT:Solr Version is 11.0.3?

**Comment by pulponair** [comment]
@dkd-kaehm actually it is 11.0.2.

**Comment by dkd-kaehm** [comment]
We can fix that issue on EXT:solr 11.5.x only, because of complexity and deep interlacement of TSFE usages and initialization in previous versions.

Unfortunately this issue was not found on searching for "default language".

I'll close that issue manually.

### Fixed in [BUGFIX] TypoScript configuration for "Hide default language" sites https://github.com/TYPO3-Solr/ext-solr/commit/ddcbc3bb6034ec3a02f410ee1a6b2ff961ff594d
