### ISSUE TITLE
Tags for Docker missing

### ISSUE THREAD

**Issue by LiohMoeller** [TYPO3-Solr/ext-solr#3125]
On https://hub.docker.com/r/typo3solr/ext-solr currently only 11.5.x-dev is listed. Is this a result of the tag restructuring? Which tags can be used for now, in relation to https://raw.githubusercontent.com/TYPO3-Solr/ext-solr/master/Documentation/Appendix/VersionMatrix.rst ?

**Comment by dkd-dobberkau** [comment]
We are currently rebuilding all docker images atm.

**Comment by mvoehringer** [comment]
@dkd-dobberkau Are you planning to rebuild the images on a regular basis perhaps? That way you could always have the latest security updates in the images.

**Comment by dkd-dobberkau** [comment]
We have pushed new tags to docker hub. 
https://hub.docker.com/r/typo3solr/ext-solr/tags
We need to evaluate if we can activate security scans on all docker repos.

**Comment by mvoehringer** [comment]
@dkd-dobberkau  will you also bring back older versions? We still have projects that use v9 or event older versions of the solr image.

**Comment by dkd-janke** [comment]
> @dkd-dobberkau will you also bring back older versions? We still have projects that use v9 or event older versions of the solr image.

Yes. WIP

**Comment by dkd-kaehm** [comment]
Current state:

Docker Images für folgende versionen wurden neu gebaut:
* EXT:solr 11.1.2 -> Apache Solr 8.9.0 (Done)
* EXT:solr 11.0.5 -> Apache Solr 8.5.2 (Done)
* EXT:solr 10.0.5 -> Apache Solr 8.2.0 (Done)
* EXT:solr 9.0.3(**New Release!**) -> Apache Solr 7.6 upgraded to 7.7.3, because 
   the official Apache Solr 7.6 Image is not a part of CVE-2021-44228  fix
   * See https://github.com/docker-solr/docker-solr/commit/d9aceb632fcad5d5e7ab42b94dd25a008f5b9112 
   * and https://hub.docker.com/_/solr?tab=tags&page=1&name=7.6
   * and https://github.com/docker-solr/docker-solr/issues/282
   * finally: https://github.com/TYPO3-Solr/ext-solr/releases/tag/9.0.3
* EXT:solr 8.1.2 -> Apache Solr 6.6.3 (triggered)
* EXT:solr 8.0.3 -> Apache Solr 6.6.3 (triggered)
* EXT:solr 7.5.3 -> Apache Solr 6.6.3 (triggered)
* EXT:solr 6.5.1 -> Apache Solr 6.6.3 (triggered)

**Comment by LiohMoeller** [comment]
Another round please 🥺 https://lists.apache.org/thread/83y7dx5xvn3h5290q1twn16tltolv88f
