### ISSUE TITLE
[BUG] Garbage collector only respects allowedPageTypes from index configuration 'pages'

### ISSUE THREAD

**Issue by DrWh0286** [TYPO3-Solr/ext-solr#3251]
**Describe the bug**
If there are multiple index configurations with `plugin.tx_solr.index.queue.[configurationName].table = pages` only `plugin.tx_solr.index.queue.pages.allowedPageTypes` is respected. This leads to deleting SOLR documents of pages, which are not indexed with configuration 'pages' because of their different doktype e.g. during editing.

**To Reproduce**
1. Configure two index configurations with table=pages and different doktypes (we use a manual added additional doktype 50 in this example, which is a special type for event pages).

```
plugin.tx_solr.index.queue {
    pages {
        allowedPageTypes = 1,7
        additionalWhereClause = (doktype = 1 OR (doktype=7 AND mount_pid_ol=0)) AND no_search = 0
        ...
    }
    
    events {
        allowedPageTypes = 50
        additionalWhereClause = (doktype = 50 AND mount_pid_ol=0) AND no_search = 0
        ...
    }
}
```

2. Add both index configurations to the queue and index them into SOLR.
3. Open an already indexed page with doktype 50 and edit e.g. page properties.
4. Now the garbage collector deletes the SOLR document for this page based on method `\ApacheSolrForTypo3\Solr\FrontendEnvironment::isAllowedPageType()`.

**Expected behavior**
The garbage collector should respect allowedPageTypes from all index configurations with table=pages, so that nothing is deleted from SOLR index.

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.31
 - Browser: Chrome (not relevant)
 - EXT:solr Version: 11.0.7
 - Used Apache Solr Version: 8.5.2
 - PHP Version: 7.3
 - MySQL Version: 5.7

**Additional context**
In depth the method `\ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration::getIndexQueueAllowedPageTypesArrayByConfigurationName()` is logical wrong. It should be something like `\ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration::getIndexQueueAllowedPageTypesArrayFromAllPagesConfigurations()`

**Comment by dkd-kaehm** [comment]
@DrWh0286 Thanks for reporting. 
The issue is known. 
The fix is to huge and most probably breaking change, so it can not be fixed quickly and if then in prospective major releases only.

It wants multiple changes and tests in multiple SQL queries and all methods taking care on "tx_solr_indexqueue_item.indexing_configuration" column and "Solr-documents.type" field values and all processes in initialization, garbage-collector and record-monitors and many more.

So this behavior will not be changed in version 11.0.x, 
therefore please try to solve this issue currently with single pages queue TypoScript configuration or may be with own page indexer.

Ralated: #1788
