### ISSUE TITLE
[BUG] Using fe_group value (-2 == show if fe_user is logged in) in page propertie logs BE user out

### ISSUE THREAD

**Issue by magicHatOfTYPO3** [TYPO3-Solr/ext-solr#3347]
**Describe the bug**

As soon ext:solr is installed and enabled in the TYPO3 system, the TYPO3 core functionality breaks. After saving a page record with fe_group value "-2" (show page if FE user is logged in, no matter which fe_group the user belongs) the BE user is logged out and have to start over. This also happens on subpages when a parent page has this setting and "extendToSubpages" is set true. 

This does not happen, if ext:solr is removed from the system. 

**To Reproduce**
1. Create new page
2. Goto page properties
3. Go to tab access and use "show if fe user is logged in" in the field fe_group
4. Click save
5. You are now logged out. 

**Expected behavior**

I expect the BE user is still logged in (as it happens if you choose a fe_user group in the named select field). 

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.16
 - Browser: chrome, firefox
 - EXT:solr Version: 11.5.0
 - Used Apache Solr Version: 8.11.1 (Docker   solr:8.11.1)
 - PHP Version: 8.0
 - MySQL Version: MariaDB 10.3

**Comment by dkd-kaehm** [comment]
Relates: #3246

**Comment by dkd-kaehm** [comment]
@magicHatOfTYPO3 
Thanks for reporting that issue. 
The kick of BE-User happens because of mentioned in #3246 core feature `"$GLOBALS['SYS']['features']['subrequestPageErrors']"`. 
Please don't use it currently together with "EXT:solr".

---

The main bug is that the TSFE can not be initialized for pages with fe_group=-2.
I'll close this issue and open a new one.
