### ISSUE TITLE
Solr 9.1.0 && ext-solr 11.5.0

### ISSUE THREAD

**Issue by clgies** [TYPO3-Solr/ext-solr#3412]
I'm not sure if Solr 9.1.0 is already supported by release 11.5.0.

If not, please ignore the following exception.

Error: Java Exception 
core_de: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core core_de: Can't load schema /var/solr/data/configsets/ext_solr_11_5_0/conf/german/schema.xml: Plugin init failure for [schema.xml] fieldType "string_collated": Error loading class 'solr.ICUCollationField'

Reproduce Error

1) Native Solr 9.1.0 installation (debian 11)
```
wget https://dlcdn.apache.org/solr/solr/9.1.0/solr-9.1.0.tgz
tar -xvf solr-9.1.0.tgz
./install_solr_service.sh ../../solr-9.1.0.tgz 
echo "SOLR_JETTY_HOST='0.0.0.0'" >> /etc/default/solr.in.sh
systemctl restart solr
```

2) checkout
git clone git clone https://github.com/TYPO3-Solr/ext-solr --branch 11.5.x

3) ext-solr: copy configsets && create default cores  

```
cp -R configsets/ cores/ solr.xml zoo.cfg /var/solr/data
mkdir -p /var/solr/data/data
chown -R solr:var/solr/data
systemctl restart solr
```

This Setup works very well with Solr 8.x.x.

**Comment by dkd-friedrich** [comment]
Hi @clgies! Thanks for the hint, in fact EXT:solr is not yet prepared for Apache Solr 9.x, but of course the compatibility is on the list.

The current supported versions and requirements can always be found in our version matrix:
=> https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Appendix/VersionMatrix.html

Probably an 11.6 will come, which supports Solr 9 eventually, otherwise EXT:solr 12 for TYPO3 12.

IMHO we can use this issue as a reminder/basis

**Comment by dkd-kaehm** [comment]
Apache Solr 9.2+ comes in EXT:solr 11.6+
