### ISSUE TITLE
[BUG] Error with fq parameter

### ISSUE THREAD

**Issue by itx-stefanie-doell** [TYPO3-Solr/ext-solr#3624]
When I made the latest minor update I observed the weirdest behavior:

In my project I use an ajax request to search and filter product data. The request is for example request?q=categoryId_stringM:(515)&fq=&type=7383 (type is the ajax configuration), the corresponding action is the resultsAction. After the update this request always results in a 404 error. When I remove the fq parameter, the result is correct. 
It does not matter if the fq parameter passes any values or is empty like in the example above.
Weirdly I only have this issue on the Mittwald server, not in my local environment. PHP Version, package versions and code are of course the same. I only found out that the Controller is initialized correctly, but the resultsAction is never reached. 
There aren't any errors, neither in the TYPO3 Log, the solr log or the php log.
I already checked the site configuration if there is any weird routing, the redirect module and the .htaccess, they are all fine.

**Used versions:**
 - TYPO3 Version:  11.5.26
 - EXT:solr Version: 11.5.2
 - PHP Version: 8.1

For me the solution was to downgrade again to 11.5.1, but I wanted you to know that there might be some kind of problem with redirects, errors or a middleware.

Thanks a lot!

**Comment by dmitryd** [comment]
@itx-stefanie-doell 

I searched for `'fq'` in the source code of EXT:solr and found nothing (`grep -R "'fq'" public/typo3conf/ext/solr/Classes/`). Where did this parameter come from? Solr uses filters like `tx_solr[filter][0]=type:pages`.

**Comment by dkd-kaehm** [comment]
@itx-stefanie-doell 
Where did `fq` parameter come from? 
I can not find anything except Apache Solrs `fq` param, which is definitely not involved in EXT:solrs JS or FE-Stack(except mapping it from [TypoScript plugin.tx_solr.search.query.filter](https://docs.typo3.org/p/apache-solr-for-typo3/solr/12.0/en-us/Configuration/Reference/TxSolrSearch.html#query-filter) [Apache Sol fq parameter](https://solr.apache.org/guide/solr/latest/query-guide/common-query-parameters.html#fq-filter-query-parameter)). Which in turn MUST NOT break through in FE-Stack.
Is it in your sources?
To avoid 404, you want to add "fq" param to the cHash ignored params.

I'll close this issue, since EXT:solr is not involved there.
