### ISSUE TITLE
Exception when I click "Queue Selected Content For Indexing" 

### ISSUE THREAD

**Issue by geraldspreer** [TYPO3-Solr/ext-solr#363]
Typo3 7.6.5
ext-solr 4.0.0

Hi there,

I get this Exception when I click "Queue Selected Content For Indexing" in the Search backend module:

```
Uncaught TYPO3 Exception
#1: PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Messaging\FlashMessageQueue::addMessage() should not be called statically, assuming $this from incompatible context in /docker/Source/web/typo3conf/ext/solr/Classes/IndexQueue/Initializer/Page.php line 215 (More information)
```

I will also submit a pull request that fixes this issue. 

Thanks,

Gerald

**Comment by timoschmidt** [comment]
We should also backport this to the 4.0.x branch.

**Comment by timoschmidt** [comment]
@geraldspreer Thx for reporting. I think this error does not occure in a TYPO3 standard installation, but anyhow we should fix it, since it is a deperaction. Can you tell me how, did you configure your 

```php
$TYPO3_CONF_VARS['SYS']['errorHandlerErrors'] & $TYPO3_CONF_VARS['SYS']['exceptionalErrors'] 
```

and error_reporting settings from the php.ini? Because in my case TYPO3 was not running at all when setting it to E_ALL and it would be nice to add this to our travis build.
