### ISSUE TITLE
[BUG] No site detected in TYPO3 12

### ISSUE THREAD

**Issue by echavaillaz** [TYPO3-Solr/ext-solr#3723]
**Describe the bug**
I use dev-main of the ext "solr" with TYPO3 12, but I don't know why, no site configured is detected. What is strange is with TYPO3 11 there is no problem. I don't change anything in the configuration.

![image](https://github.com/TYPO3-Solr/ext-solr/assets/11553717/14ac8417-536d-41a1-aab1-32137ff6fd02)
![image](https://github.com/TYPO3-Solr/ext-solr/assets/11553717/67771eef-d772-43b9-a3ef-2f892d9a8f03)

If I comment the line 174 ($tsfe->getFromCache($serverRequest);) in "Classes/FrontendEnvironment/Tsfe.php", this is better:

![image](https://github.com/TYPO3-Solr/ext-solr/assets/11553717/e00681b6-1d44-484d-9477-c58ce2c25bcd)

But in the the module "Index Queue" I got an error:

![image](https://github.com/TYPO3-Solr/ext-solr/assets/11553717/b3db2fed-a36d-424c-8d27-ea8e09ea6c10)

**Used versions**
 - TYPO3 Version:12.4.3
 - Browser: all
 - EXT:solr Version: dev-main
 - Used Apache Solr Version: 9.2.1
 - PHP Version: 8.1.16

**Comment by dkd-kaehm** [comment]
Most probably, the TSFE can not be initialized for root page.
Please check the Rootpage is not access restricted.
See if #3708 helps

**Comment by dkd-kaehm** [comment]
> If I comment the line 174 ($tsfe->getFromCache($serverRequest);) in "Classes/FrontendEnvironment/Tsfe.php", this is better:

Does work all without this line?

https://github.com/TYPO3-Solr/ext-solr/blob/d9e4f9dacc2d5212d462c5867309ce6a198f8595/Classes/FrontendEnvironment/Tsfe.php#L174

**Comment by echavaillaz** [comment]
> 

No restriction on the root page.

**Comment by dkd-kaehm** [comment]
@echavaillaz 
Is the Instance in composer mode?
What happens on Stable release?

**Comment by echavaillaz** [comment]
Yes it is in composer mode, with the stable release I got : "Call to a member function getSolrConfiguration() on null"

**Comment by dkd-kaehm** [comment]
@echavaillaz
please post whole trace of "Call to a member function getSolrConfiguration() on null", because `getSolrConfiguration() ` is used on multiple places

Is there more than one root page(if so, is root or sub page selected in page tree)?

Did you flush the caches via Maintenance module?

Can you post your site-config(anonymized with ****** ) and the extensions list?

Is xDebug available on this environment?

**Comment by echavaillaz** [comment]
After a deep debugging I found the exception how break my Solr configuration.
In fact I have TS condition like `[like(request.getNormalizedParams().getRequestUri(), '*')]` and it break the TSFE init in Solr.

After fixing like describe here https://forge.typo3.org/issues/89715, all is fine.

So we can close this issue.
Thanks for the help.

**Comment by abohntek** [comment]
@dkd-kaehm, I am experiencing the exact same behavior as described. As soon as I comment out $serverRequest = $tsfe->getFromCache($serverRequest);, I at least establish a connection, but still receive the message that no site could be found inside the "Index Queue" module.

Throughout my entire TypoScript condition and in all extensions I am using, there is no condition like like(request.getNormalizedParams().getRequestUri...) in use.

Versions Used:

- TYPO3 Version:12.4.8
- EXT:solr Version: 12.0.1
- Used Apache Solr Version: 9.3.0
- PHP Version: 8.1.11

There are also no restrictions set on any root page. I have a multi-site Typo3 instance with several root pages. The root page is selected, with no sub-page. I have flushed the maintenance cache dozens of times. Composer mode is enabled, and it is a ddev setup. My site configuration for one of the root pages is actually straightforward:

[config.txt](https://github.com/TYPO3-Solr/ext-solr/files/13460654/config.txt)

Perhaps someone has an idea of what is causing the error.

**Comment by dkd-kaehm** [comment]
> [config.txt](https://github.com/TYPO3-Solr/ext-solr/files/13460654/config.txt)
> 
> Perhaps someone has an idea of what is causing the error.

@abohntek 
Try to add the schema on base:
`base: //site.at` to `base: https://site.at`
And look into the reports module.

**Comment by balatD** [comment]
@dkd-kaehm same here! I installed the solr extesnion on a mostly fresh TYPO3 v12 system. Configured it and the reports module shows that my base site configuration is fine. If I comment out the $tsfe line, mentioned above, I am getting a connection but still the index queue shows "no site configured".

TYPO3 12.4.8
Solr: 12.0.1
PHP: 8.2

**Comment by abohntek** [comment]
In my case it was the TS condition 

```
[!ip("{$restriction.ipRange}") and {$pages.PIDs.menu.restrictedPid} in tree.rootLineIds]
    page.10 >
    page.headerData.10 = TEXT
    page.headerData.10.value = <meta http-equiv="refresh" content="0; url={$config.baseURL}">
[end]
```
which caused the problem.

**Comment by keessonnema** [comment]
I found this when migrating to TYPO3 12. I have a similar issue as @abohntek where the ip() condition breaks the Solr Connection.
```
[ip("{$kccknowledge.ipList}")]
  plugin.tx_solr.search.query {
    queryFields := addToList(<boosting fields here>)
    filter {
      noContent >
      noProducts >
    }
  }
[end]
```

**Comment by Apen** [comment]
Can add my feedback too for this problem :-)

I have a very large instance with mutiple root pages. The bug was the same "No site detected" but i have nothing in all the log about typoscript parsing problem.

It was a conditionnal with "request.getNormalizedParams().getRequestUri()" so i make the same correction as above. 

With this, my site was detected (in index module too). But this instance have a lot of TS and the chaing process leed to a memory_limit problem wich i have been solved with php.ini modification. However, the module is veeeeery slow but functionnal. Didnt take time to profile this problem

**Comment by dkd-kaehm** [comment]
> Can add my feedback too for this problem :-)
> 
> I have a very large instance with mutiple root pages. The bug was the same "No site detected" but i have nothing in all the log about typoscript parsing problem.
> 
> It was a conditionnal with "request.getNormalizedParams().getRequestUri()" so i make the same correction as above.
> 
> With this, my site was detected (in index module too). But this instance have a lot of TS and the chaing process leed to a memory_limit problem wich i have been solved with php.ini modification. However, the module is veeeeery slow but functionnal. Didnt take time to profile this problem

Did you tried the delayed mode? 
https://docs.typo3.org/p/apache-solr-for-typo3/solr/12.0/en-us/Configuration/Reference/ExtensionSettings.html?highlight=delayed#monitoringtype

**Comment by Apen** [comment]
@dkd-kaehm 
Sure i use it since a long time :-)
This is the "Solr Info" module and the "Solr Index" one who are very slow.

I have made a rapid blackfire profiling of 30 seconds for a website with 75 websites.
If you want i can provide you a link in DM.

After a fast check :
- TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getFromCache call 75x = 35 seconds
- TYPO3\CMS\Core\TypoScript\IncludeTree\SysTemplateTreeBuilder::getTreeBySysTemplateRowsAndSite = 60% of the time
- TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser::traverse = 22%  of the time

There must be optimization there and the blackfire link could help you if you want.
