### ISSUE TITLE
[BUG] Core error exception - Undefined array key "label" in AbstractFormElement.php line 146

### ISSUE THREAD

**Issue by galinei** [TYPO3-Solr/ext-solr#3739]
In TYPO3 12.4.4, in the backend module 'Index Queue', I get the error:

![Screenshot from 2023-07-28 16-37-08](https://github.com/TYPO3-Solr/ext-solr/assets/2262305/c151d603-788a-43e2-9ca9-126a09169c03)

Adding the line:

`$options['parameterArray']['fieldConf']['label'] = '';`

in
https://github.com/TYPO3-Solr/ext-solr/blob/4dd5d415e2c69bde292ac6ec8cd3f65cd5ad3cbd/Classes/Backend/IndexingConfigurationSelectorField.php#L205
removes the error.

**Comment by dkd-kaehm** [comment]
@galinei 
Is it not fixed with https://github.com/TYPO3-Solr/ext-solr/commit/35de99d160a7d2296e65f29a07b52d46490fc352 ?
Which EXT:solr version is used?
For next issues, please use [our issue template](https://github.com/TYPO3-Solr/ext-solr/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=%5BBUG%5D+Please+add+a+speaking+title) .

**Comment by galinei** [comment]
version: 12.0.0-beta-1
I've switched to main.
Thanks!
