### ISSUE TITLE
[TASK]  Record Monitor cannot track records outside a site

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#485]
A common scenario is to have a site and a storage folder for records parallel to it on the same level (f.e.)

Currently the Record Monitor tries to find the indexing configuration on a record's parent page (pid). For such a scenario the site cannot be found and thus no configuration can be determined, leading to the record not being updated in the Index Queue and also not being re-indexed.

---

https://forge.typo3.org/issues/31519
https://forge.typo3.org/issues/42521
https://forge.typo3.org/issues/43349
https://forge.typo3.org/issues/47110
https://forge.typo3.org/issues/55701

Outside the site root the indexing configuration is not available, but it should be possible to check all existing site roots. 

Value: 20
Effort: 13

**Comment by irnnr** [comment]
Possible solution:

* detect if a sys folder is located within a tree with a root page
* if that is not the case add a (multi-)select field to sys folder page properties
* the select field shows the available sites configured for Solr indexing
* this way the user can select which configurations should apply to that folder

**Comment by AndreasA** [comment]
In that regard it would also be good to have a setting that allows tables that have set TCA
```
'rootLevel' => true
```
set to be monitored and initialized.

Due to it being the pageId 0 setting
```
additionalPageIds = 0
```
will fail due the empty check 
```
if (!empty($this->indexingConfiguration['additionalPageIds']))
```

As workaround one could set 
```
additionalPageIds = 00
```
or similar but it would be nice if that were "easier"

**Comment by irnnr** [comment]
that's a different issue, and IMHO indexing from root page should not be possible at all

**Comment by AndreasA** [comment]
Well, I have a task that imports data via SOAP-interface therefore those data isn't editable, not even viewable (hideTable => true). So storing it at page 0 makes sense as that page will never be deleted.
However, it should be indexed in solr.
I could import it directly to solr but I also need that data as reference in other tables, so it is just easier to import it to the database and use default typo3 features for it (suggest etc.)

Therefore, there are cases where indexing such data can make sense. Probably not often the case but still.
In my case I am now importing the data now to the web root as that page is very unlikely to be deleted :)
And it is related to the additionalPageIds which is why I mentioned it here but I can create a own bug if that is better.

**Comment by dkd-dobberkau** [comment]
I remember times, when we used a sysfolder holding that kind of general data. no need for packing the root page with payload.

**Comment by irnnr** [comment]
@AndreasA You're describing an edge use case - for the intended purpose of this extension at least. You could work around this by constructing and indexing Solr documents yourself while importing you SOAP data. Alternative 2 is to import into a folder instead of the root page.

Either way, root page indexing is not related to this issues' topic of indexing from out-of-site folder.

**Comment by NamelessCoder** [comment]
Just my vote here from the sidelines (working on a related issue): indeed, indexing using explicit page UID zero should not be possible. There will be no defined connection, and that alone should be reason enough to not index the very root page.

**Comment by AndreasA** [comment]
There will be no defined connection for any pages defined with additionalPageIds which is the reason why the setting is there.
So, if you ask me, either remove the option to index pages outside the current root page (additionalPageIds) altogether or make it work with the root page too because then page 0 is just another page.
