### ISSUE TITLE
Problem with indexing of pages and tt_content

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#717]
We have enabled indexing of both pages and tt_content. We made an initial indexing of the whole site which is fine. If we add or modify tt_content elements afterwards only the page is updated and not the tt_content element. This is due to the following code in RecordMonitoring.
{code}
```
// when a content element changes we need to updated the page instead
if ($recordTable == 'tt_content') {
   error_log("Hitting this one");
   $recordTable = 'pages';
   $recordUid = $recordPageId;
}
```
In our opinion both the tt_content element and the page should be update. 
We could provide a path for this if desired

**Comment by timohund** [comment]
@irnnr Do you think it's possible when tt_content is updated to queue tt_content and pages, when there is an seperate indexing configuration for tt_content?

**Comment by irnnr** [comment]
This is not how page indexing works. Page indexing works on the pages table only. This is a design decision made on purpose since tt_content and pages have special behavior in TYPO3. The core handles them differently than regular records, so does the solr extension.

You cannot index just tt_content records because of all the possible implications of access control and templating. You cannot calculate what content element is rendered on what page at what time for which users. The system is too flexible for that. The only proper way to index content is by rendering the pages.

**Comment by thomashohn** [comment]
@irnnr and @timohund I might be as you describe. But if I make pages and tt_content elements and configure them for indexing - the access restrictions are stored correctly in solr and respected when searches are performed. The problem here seems to be that upon updates of tt_content elements then these updates are not propagated properly to the database due to this. I'll talk to Claus Due und my collegue who where the ones defining this indexing of tt_content element.
I guess a workaround in my case could be to hook into processDatamap_afterDatabaseOperations and handle it there even though I would have been nice to have a handle on that in the core of solr

**Comment by irnnr** [comment]
edge case is the word you're looking for ;)

**Comment by thomashohn** [comment]
@irnnr / @timohund Point taken. At least it would then be nice if the actual processing of the record could be placed in a method call - in that way the processing would be decoupled from the calculation of what to process - I could live with that :-)
