### ISSUE TITLE
Add new configuration plugin.tx_solr.statistics.addDebugData

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#865]
Today the enabling of `plugin.tx_solr.statistics` triggers that debugMode is added to the Solr query. This is apparently necessary in order to fill 3 database columns (`time_total, time_preparation, time_processing`) properly for the table `tx_solr_statistics`.

However these 3 columns are not used in the statisticsmodule today - might not even come - and imposes a performance impact of approximately 25-30% pr. search just in order to be able display basic statistics that does not even include these 3 columns.

We would like to propose that a new configuration `plugin.tx_solr.statistics.addDebugData` is added. The purpose should be to be able to control if the debugMode is added or not to the search query.

We have provide a PR that implements this - see #866

**Comment by timohund** [comment]
Hi Thomas,

thanks for your pull request! I don't think we should merge it like this because of the following reasons:

1. plugin.tx_solr.advancedStatistics should be somewhere below plugin.tx_solr.statistic e.g. (plugin.tx_solr.statistics.addDebugData)

2. Storing the statistics in the database i only reasonable for small systems. When performance is an issue i would suggest to turn off the statistic and use a tool that is optimized for this usecase (e.g. piwik, or google analystics). Otherwise we add more and more logic to a part where systems exist that do this job better.

What do you think?

**Comment by irnnr** [comment]
+1 on both thoughts
