### ISSUE TITLE
CONF_VARS Setting FE:disableNoCacheParameter should be set to false when disabling caching

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#871]
If one sets:
```
$GLOBALS['TYPO3_CONF_VARS']['FE']['disableNoCacheParameter'] = true;
```

TYPO3 doesn't allow to disable the cache for a page.
It should still set no_cache correctly, however, TYPO3 ensures that if the cache was not set before page generation that it hasn't been modify by a script.
However, that only works correctly if 
```
$GLOBALS['TYPO3_CONF_VARS']['FE']['disableNoCacheParameter'] = false;
```

which is why solr should also set this parameter to false when disabling cache.

**Comment by AndreasA** [comment]
Maybe even better would be a solution that avoids any syslog entries.
Maybe adding a settingLanguage_postProcess Hook that sets no_cacheBeforePageGen to false (and sets no_cache again)
and a contentPostProc-all that resets adds no_cache again (as that is where no_cacheBeforePageGen would be used otherwise)

**Comment by timohund** [comment]
@AndreasA can you provide a patch for this?

**Comment by AndreasA** [comment]
Not in the immediate future but in general yes :)

**Comment by AndreasA** [comment]
Sorry, for the delay I forgot about the ticket.
However, it will probably best if someone else creates a PR because I recently switched jobs and we don't use solr search there, so I am not sure when / if I will take the time for this.

**Comment by 3l73** [comment]
The configuration `disableNoCacheParameter` is checked in two places:

1. `\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::set_no_cache`  which trigger the internal function `TypoScriptFrontendController::disableCache` that set property `no_cache` to false
2. `\TYPO3\CMS\Frontend\Middleware\PageArgumentValidator::process`

Since the property `no_cache` inside the class TypoScriptFrontendController is public and Solr access this variable directly, no change is required for 1.

**Comment by 3l73** [comment]
Since Solr access the property no_cache directly inside the TypoScriptController, I think, this issue is obsolet.

The Page indexer it self did not set the parameter `no_cache`, so there is no need for a hook or a pull request.

However, if this becomes an issue again, please open a new Pull-Request.
