### ISSUE TITLE
[BUG] Invalid include paths after scheduler run

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#921]
With current EXT:solr (6.1.0-dev) and TYPO3 master (8.6.0-dev) invalid include paths occur if the Index Queue Worker is started from backend and processes queue items.

An example for an invalid include path is `typo3/typo3/sysext/backend/Resources/Public/Css/backend.css`

**Comment by thomashohn** [comment]
@timohund,@dkd-friedrich,@irnnr   Seems to be some kind of weird problem that occurs when restore is called in CliEnvironment. 
1) First observation - if restored is called an there is nothing to index the error does NOT occur.
2) Second observation - disable restore seem to "work"

**Comment by timohund** [comment]
@thomashohn @dkd-friedrich @irnnr When we fix this we need to take the issue into account where the set and restore of the environment was done. There where several issues that the urls are not generated properly with absRefPrefix.

**Comment by thomashohn** [comment]
Look into the "original" issue that should solve this. Seems that the original problem was when calling the Task from the "command-line" via cli. Also took a talk with @NamelessCoder about the topic an it seems that the "CliEnvironment" should really on be instantiated and used when called from cli and not the backend. Suggestion is to wrap this calls into a check via the TYPO3 `EnvironmentService` or `if (TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI)`

**Comment by dkd-friedrich** [comment]
@thomashohn @timohund @irnnr Thanks for your investigations, Thomas. I haven't double-checked it, but I think it should be save to adapt the environment in CLI mode only. The environment adaptions were introduced within issue #491 which only mentioned problems in CLI context.

I also had a look at the problem's causes, `CliEnvironment` defines the constant `TYPO3_PATH_WEB` which leads to a different approach of determining the `TYPO3_SITE_URL`. If `TYPO3_PATH_WEB` is set, `getIndpEnv()` uses the `TYPO3_REQUEST_DIR` (`TYPO3_REQUEST_HOST` & `SCRIPT_NAME`) instead of `PATH_thisScript`. Interestingly the determined `TYPO3_SITE_URL` is correct if we skip the restore of the old environment. Perhaps this is an other option to discuss if we're not sure if the environment adaptions can be limited to the CLI context.

**Comment by thomashohn** [comment]
Personally I think I'm more into the solution where we only adapt the environment in CLI mode only. I don't think it's advisable to mess around with these values unless you are in the CLI mode. If you have time to test - I could come up with a PR for that?

**Comment by NamelessCoder** [comment]
Generally speaking, you should definitely avoid changing any of those constants, or depending on them having a different value in one case vs another case.

Also, there is a logical disconnect by providing the `TYPO3_SITE_URL` on CLI since this context has no URLs. The value can be affected by various HTTP server virtual host and TS configuration options, as you've found out.

So there may be some factors here that mean it's better to somehow restrict this CLI indexing so it simply will not generate any frontend URLs because doing this involves either a lot of context manipulation or manually patching/resolving the context needed to generate a URL. Which by the way may end up being completely incorrect since CLI knows nothing about the virtual host and the site may in fact be served on multiple different virtual hosts which all have a different URL.

Fooling TYPO3 into thinking it "sort of" is in frontend context is usually not a good idea.

As an example of such difficulties you may want to take a look at the `f:format.html` ViewHelper and its demand for a complete FE context, meaning it can't be used predictably in either BE or CLI modes. The amount of work that was required to even remotely get this working, was extreme and is still ongoing after close to two years. Basically, the approach is to remove all coupling to a particular context from everything that one could possibly render in a vanilla RTE using any option the core supports. You'll face much the same of this, though not in as large a scale (given that URL generation is somewhat easier to manage than a full set of RTE options).

**Comment by timohund** [comment]
@NamelessCoder i agree. I think the root of the problems is "The need to generate a frontent context, in backend context or cli mode" and currently this frontend context is needed to:

* Get the real content of the page with all conditions (typoscript, language, permissions,...)
* The indexing needs to be scheduled an continuosly done (therefore currently cli is used)

So my question would be, how could this be resolved?

**Comment by NamelessCoder** [comment]
> So my question would be, how could this be resolved?

One way would be to perform the indexing on a special typeNum that you provide a real page UID, language etc. for. That can then be triggered from CLI with status reporting, and you can either transfer the data as response or have the HTTP put it directly in the DB. The scheduler task can then be fitted with an option to set the HTTP hostname and you can silently generate a key/token for the request that will be made.

So far this is the only consistent solution I've found to the "indexing needs FE" problem. It has shown to be the only way to prevent issues, because anything that you can render in FE may cascade rendering to TS which may implement conditions and render literally every possible TS object with fan-outs to extension code, plugin rendering, etc.

**Comment by timohund** [comment]
For me this sound like a good idea by looking at all circustances, to have a frontend api on a type that could compile the "source of through", the "only" challange that i see by now is the efford because this has an impact on all components (solr, solrfal). Which means we need the resources for that.

**Comment by NamelessCoder** [comment]
I realise it's no small thing to recommend. You maybe could start small by wrapping these indexing dispatches in an API and use this throughout - then you only have one place to refactor to change the method of indexing and can even make a toggle for it.

Despite the gloom and doom above (which I learned the hard way) there *are* use cases which simply don't need to call the FE in order to index things correctly. However, those aren't the prevalent use cases and they require an extreme amount of attention to detail and control over everything that can possibly be rendered by the site.

**Comment by timohund** [comment]
I would propse for now to fix this issue with the current indexing and create a seperate issue for an indexing with a seperate pagetype.

**Comment by NamelessCoder** [comment]
Sure thing - to fix this problem at hand, the conditions Thomas quoted can be quickly implemented; the direct `if (TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI)` is frequently used in the core.

**Comment by timohund** [comment]
Fixed with #936
